# version: '3.8'
services:
  server_hello:
    image: tigase/tigase-xmpp-server:8.0.0
    ports:
      - "8480:8080"
      - "5422:5222"
    environment:
      - DB_ROOT_USER=admin
      - DB_ROOT_PASS=admin
      - ADMIN_JID=admin@server_hello
      - ADMIN_PASSWORD=admin
      - REPORTER_JID=reporter@server_hello
      - REPORTER_PASSWORD=reporter
      - GOOGLE_OPINIONHANDLER_JID=google_opinion_handler@server_hello
      - GOOGLE_OPINIONHANDLER_PASSWORD=google_opinion_handler
      - BOOKING_OPINIONHANDLER_JID=booking_opinion_handler@server_hello
      - BOOKING_OPINIONHANDLER_PASSWORD=booking_opinion_handler
      - FACEBOOK_OPINIONHANDLER_JID=facebook_opinion_handler@server_hello
      - FACEBOOK_OPINIONHANDLER_PASSWORD=facebook_opinion_handler
      - TRIPADVISOR_OPINIONHANDLER_JID=tripadvisor_opinion_handler@server_hello
      - TRIPADVISOR_OPINIONHANDLER_PASSWORD=tripadvisor_opinion_handler
      - CITY_DEPARTMENTHANDLER_JID=city_department_handler@server_hello
      - CITY_DEPARTMENTHANDLER_PASSWORD=city_department_handler
      - DISTRICT_DEPARTMENTHANDLER_JID=district_department_handler@server_hello
      - DISTRICT_DEPARTMENTHANDLER_PASSWORD=district_department_handler
      - STREET_DEPARTMENTHANDLER_JID=street_department_handler@server_hello
      - STREET_DEPARTMENTHANDLER_PASSWORD=street_department_handler
      - CUSTOMER_AGENT_JID=customer_agent@server_hello
      - CUSTOMER_AGENT_PASSWORD=customer_agent
      - ALLEGRO_PRICEHANDLER_JID=allegro_price_handler@server_hello
      - ALLEGRO_PRICEHANDLER_PASSWORD=allegro_price_handler
      - OLX_PRICEHANDLER_JID=olx_price_handler@server_hello
      - OLX_PRICEHANDLER_PASSWORD=olx_price_handler
      - OTODOM_PRICEHANDLER_JID=otodom_price_handler@server_hello
      - OTODOM_PRICEHANDLER_PASSWORD=otodom_price_handler
    volumes:
      - ./tigase/config/tigase.conf:/home/tigase/tigase-server/etc/tigase.conf
      - ./tigase/config/config.tdsl:/home/tigase/tigase-server/etc/config.tdsl



  aasd:
    image: aasd:latest
    depends_on:
      - server_hello
    environment:
      - DB_ROOT_USER=admin
      - DB_ROOT_PASS=admin
      - ADMIN_JID=admin@server_hello
      - ADMIN_PASSWORD=admin
      - REPORTER_JID=reporter@server_hello
      - REPORTER_PASSWORD=reporter
      - GOOGLE_OPINIONHANDLER_JID=google_opinion_handler@server_hello
      - GOOGLE_OPINIONHANDLER_PASSWORD=google_opinion_handler
      - BOOKING_OPINIONHANDLER_JID=booking_opinion_handler@server_hello
      - BOOKING_OPINIONHANDLER_PASSWORD=booking_opinion_handler
      - FACEBOOK_OPINIONHANDLER_JID=facebook_opinion_handler@server_hello
      - FACEBOOK_OPINIONHANDLER_PASSWORD=facebook_opinion_handler
      - TRIPADVISOR_OPINIONHANDLER_JID=tripadvisor_opinion_handler@server_hello
      - TRIPADVISOR_OPINIONHANDLER_PASSWORD=tripadvisor_opinion_handler
      - CITY_DEPARTMENTHANDLER_JID=city_department_handler@server_hello
      - CITY_DEPARTMENTHANDLER_PASSWORD=city_department_handler
      - DISTRICT_DEPARTMENTHANDLER_JID=district_department_handler@server_hello
      - DISTRICT_DEPARTMENTHANDLER_PASSWORD=district_department_handler
      - STREET_DEPARTMENTHANDLER_JID=street_department_handler@server_hello
      - STREET_DEPARTMENTHANDLER_PASSWORD=street_department_handler
      - CUSTOMER_AGENT_JID=customer_agent@server_hello
      - CUSTOMER_AGENT_PASSWORD=customer_agent
      - ALLEGRO_PRICEHANDLER_JID=allegro_price_handler@server_hello
      - ALLEGRO_PRICEHANDLER_PASSWORD=allegro_price_handler
      - OLX_PRICEHANDLER_JID=olx_price_handler@server_hello
      - OLX_PRICEHANDLER_PASSWORD=olx_price_handler
      - OTODOM_PRICEHANDLER_JID=otodom_price_handler@server_hello
      - OTODOM_PRICEHANDLER_PASSWORD=otodom_price_handler
    volumes:
      - ./src:/app/src
      - ./data:/app/data
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 512MB
